export const palettes = [
  {
    id: 1,
    name: "default",
    type: "dark",
    colors: {
      primary: "#3A4750",
      secondary: "#303841",
      textDark: "#5e6c7d",
      text: "#859aab",
      textLight: "#ebf3fa",
      white: "#fff",
    },
  },
  {
    id: 2,
    name: "niew",
    type: "dark",
    colors: {
      primary: "#372948",
      secondary: "#251B37",
      textDark: "#876969",
      text: "#FFCACA",
      textLight: "#FFECEF",
      white: "#fff",
    },
  },
  {
    id: 3,
    name: "xhle",
    type: "light",
    colors: {
      primary: "#9795CF",
      secondary: "#64638F",
      textDark: "#ABA9E9",
      text: "#CBC9FF",
      textLight: "#e4e3fc",
      white: "#fff",
    },
  },
  {
    id: 4,
    name: "lemo",
    type: "light",
    colors: {
      primary: "#749F82",
      secondary: "#425F57",
      textDark: "#94b861",
      text: "#A8E890",
      textLight: "#f4ffe6",
      white: "#fff",
    },
  },
  {
    id: 5,
    name: "psky",
    type: "light",
    colors: {
      primary: "#4D4C7D",
      secondary: "#363062",
      textDark: "#827397",
      text: "#baa5d9",
      textLight: "#D8B9C3",
      white: "#fff",
    },
  },
  {
    id: 6,
    name: "tree",
    type: "light",
    colors: {
      primary: "#4E6C50",
      secondary: "#395144",
      textDark: "#AA8B56",
      text: "#F0EBCE",
      textLight: "#f2c67c",
      white: "#fff",
    },
  },
  {
    id: 7,
    name: "sugar",
    type: "light",
    colors: {
      primary: "#FF639F",
      secondary: "#FF2865",
      textDark: "#852047",
      text: "#f2ecbf",
      textLight: "#fffbde",
      white: "#fff",
    },
  },
  {
    id: 8,
    name: "carpet",
    type: "dark",
    colors: {
      primary: "#B25068",
      secondary: "#774360",
      textDark: "#db7d30",
      text: "#E7AB79",
      textLight: "#f7d6ba",
      white: "#fff",
    },
  },
  {
    id: 9,
    name: "yelly",
    type: "light",
    colors: {
      primary: "#D5A4CF",
      secondary: "#B689B0",
      textDark: "#fce25d",
      text: "#FFF1AC",
      textLight: "#fffae0",
      white: "#fff",
    },
  },
  {
    id: 10,
    name: "new",
    type: "dark",
    colors: {
      primary: "#815B5B",
      secondary: "#594545",
      textDark: "#9E7676",
      text: "#FFF8EA",
      textLight: "#fcfbf7",
      white: "#fff",
    },
  },
];
